const TABLE = {
	MEMBER : 'tb_member',
	USERS : 'tb_users',
	SEND_MAIL : 'tb_send_mail',
	CONFIG : 'tb_config',	
	WORKSITE: 'tb_worksite',
	GRPCODE: 'tb_grpcode',
	COMCODE: 'tb_comcode',
	HRBASE: 'tb_hrbase',
	VEND: 'tb_vend',
	ITEM: 'tb_item',
	PROCESS: 'tb_process',
	PROCESSTYPE: 'tb_ptype',
	PROCESSTYPELIST: 'tb_ptypeli',
	ROUTE: 'tb_route',
	ROUTEPROC: 'tb_routeproc',
	ESTIMATE: 'tb_estimate',
	ESTIMATELI: 'tb_estimateli',
	ORDER: 'tb_order',
	ORDERLI: 'tb_orderli',
	PRODPLAN: 'tb_prodplan',
	PRODMAKE: 'tb_prodmake',
	NOTICE: 'tb_notice',
	SHIPMENT: 'tb_prodship',
	INVOICE: 'tb_invoice',
	INVOICELI: 'tb_invoiceli',
	ACCOUNT: 'tb_account',
    OPENLOG: 'tb_openlog',
	KPI1: 'tb_kpilevel1',
	KPI2: 'tb_kpilevel2',
	KPI3: 'tb_kpilevel3',
};

module.exports = TABLE;